const topics=window.brochureTopics,sources=window.brochureSources,selected=new Set();
const panel=document.querySelector('#topic-panel'),nav=document.querySelector('.topic-nav'),dialog=document.querySelector('#plan-dialog');
const icons={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',book:'<path d="M12 5v16M12 5C8 2 3 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-4-2-7-1-10 1Z"/>',people:'<circle cx="8" cy="7" r="3"/><circle cx="18" cy="9" r="2.5"/><path d="M2 21v-3a6 6 0 0 1 12 0v3m2-6a5 5 0 0 1 6 5v1"/>',check:'<rect x="4" y="3" width="16" height="19" rx="3"/><path d="m8 12 3 3 5-6"/>'};
function announce(t){document.querySelector('#live-status').textContent=t}
function questionId(t,i){return t.id+'-'+i}
function renderTopic(id,focus=false){const t=topics.find(x=>x.id===id)||topics[0];nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.id===t.id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});panel.setAttribute('aria-labelledby','tab-'+t.id);const s=sources[t.source];panel.innerHTML=`<div class="panel-label"><p class="eyebrow">ONDERWERP ${t.n} / 04</p><svg class="topic-symbol" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[t.icon]}</svg></div><h3>${t.title}</h3><p class="panel-intro">${t.intro}</p>${t.sections.map((x,i)=>`<details class="explain" ${i===0?'open':''}><summary>${x.title}</summary><p>${x.text}</p></details>`).join('')}<aside class="example"><p class="label">${t.example.title}</p><p>${t.example.text}</p></aside><div class="questions"><h4>Neem mee naar het gesprek</h4>${t.questions.map((q,i)=>`<label class="question"><input type="checkbox" value="${questionId(t,i)}" ${selected.has(questionId(t,i))?'checked':''}><span>${q}</span></label>`).join('')}</div><p class="source-line">Lees verder bij <a href="${s.url}" target="_blank" rel="noopener">${s.name} ↗</a></p>`;panel.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{input.checked?selected.add(input.value):selected.delete(input.value);updateCount();announce(input.checked?'Vraag toegevoegd aan je gesprekslijst.':'Vraag verwijderd uit je gesprekslijst.')}));if(focus)panel.focus({preventScroll:true});}
function updateCount(){document.querySelector('#count').textContent=selected.size;document.querySelectorAll('.plan-trigger').forEach(b=>b.setAttribute('aria-label',`Mijn gesprekslijst, ${selected.size} vragen`));}
topics.forEach((t,i)=>{const b=document.createElement('button');b.type='button';b.className='topic-tab';b.id='tab-'+t.id;b.dataset.id=t.id;b.setAttribute('role','tab');b.setAttribute('aria-controls','topic-panel');b.innerHTML=`<span class="num">${t.n}</span><span><span class="title">${t.title}</span><span class="short">${t.short}</span></span><span class="arrow" aria-hidden="true">↗</span>`;b.addEventListener('click',()=>renderTopic(t.id));b.addEventListener('keydown',e=>{let j=i;if(['ArrowRight','ArrowDown'].includes(e.key))j=(i+1)%topics.length;else if(['ArrowLeft','ArrowUp'].includes(e.key))j=(i+topics.length-1)%topics.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=topics.length-1;else return;e.preventDefault();renderTopic(topics[j].id);nav.children[j].focus()});nav.append(b)});
function groups(){return topics.map(t=>({...t,items:t.questions.map((text,i)=>({text,id:questionId(t,i)})).filter(q=>selected.has(q.id))})).filter(t=>t.items.length)}
function updatePlan(){const target=document.querySelector('#plan-content');const g=groups();target.innerHTML=g.length?g.map(t=>`<section class="plan-group"><h3>${t.n} · ${t.title}</h3>${t.items.map(q=>`<div class="plan-item"><span>${q.text}</span><button type="button" class="remove-item" data-id="${q.id}" aria-label="Verwijder vraag: ${q.text}">Verwijder</button></div>`).join('')}</section>`).join(''):'<div class="empty-plan"><p>Je hebt nog geen vragen gekozen. Vink bij een onderwerp de vragen aan die je wilt bespreken.</p><button type="button" class="button secondary" id="choose-questions">Vragen kiezen →</button></div>';target.querySelectorAll('.remove-item').forEach(b=>b.addEventListener('click',()=>{selected.delete(b.dataset.id);const active=nav.querySelector('[aria-selected=true]').dataset.id;renderTopic(active);updateCount();updatePlan();const next=target.querySelector('.remove-item')||document.querySelector('#choose-questions');if(next)next.focus();announce('Vraag verwijderd.')}));document.querySelector('#choose-questions')?.addEventListener('click',()=>{dialog.close();document.querySelector('#onderwerpen').scrollIntoView();nav.querySelector('[aria-selected=true]').focus({preventScroll:true})});document.querySelector('#print-plan').disabled=!g.length;document.querySelector('#download-plan').disabled=!g.length;}
document.querySelectorAll('.plan-trigger').forEach(b=>b.addEventListener('click',()=>{updatePlan();dialog.showModal()}));document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function renderPrint(){document.querySelector('#print-sheet').innerHTML=`<h1>Weer naar school</h1><p>Gesprekslijst voor leerling, ouders en school</p><p>Gespreksdatum: ____________________ &nbsp; Aanspreekpunt: ____________________</p>${groups().map(t=>`<h2>${t.title}</h2>${t.items.map(q=>`<div class="print-question">${q.text}<div class="write-line"></div><div class="write-line"></div></div>`).join('')}`).join('')}<h2>Wie doet wat? Wanneer bespreken we hoe het gaat?</h2><div class="write-line"></div><div class="write-line"></div><p class="print-footer">School & herstel · Demonstratie-uitgave van Marcel Mutsaarts · Geen officiële Ziezon-uitgave.<br>Praktische gesprekshulp. Medische afspraken bespreek je met de behandelaar.</p>`}
document.querySelector('#print-plan').addEventListener('click',()=>{renderPrint();window.print()});window.addEventListener('beforeprint',renderPrint);
document.querySelector('#download-plan').addEventListener('click',()=>{const text='WEER NAAR SCHOOL\nMijn gesprekslijst\n\n'+groups().map(t=>t.title+'\n'+t.items.map(q=>'[ ] '+q.text+'\n    Afspraak / eigenaar / moment:').join('\n\n')).join('\n\n')+'\n\nSchool & herstel | Demonstratie-uitgave Marcel Mutsaarts\nGeen officiële Ziezon-uitgave.';const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mijn-gesprekslijst.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);announce('Je gesprekslijst is gedownload.');});
renderTopic(topics[0].id);updateCount();
